package eu.relay4u.prospecting.exception;

public enum ErrorCode {
    VALIDATION_FAILED,
    BAD_REQUEST,
    PROJECT_NOT_FOUND,
    FIELD_KEY_CONFLICT,
    INVALID_FIELD_VALUE,
    ACCESS_DENIED,
    INTERNAL_ERROR,
    MEMBER_ALREADY_EXIST,
    INVITATION_NOT_FOUND
}
